//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adventureworks.Domain5
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ProductPhoto
    {
    	public ProductPhoto()
    	{
    		this.ProductProductPhotoes = new HashSet<ProductProductPhoto>();
    	}
    
    	[Key]
		public int ProductPhotoID { get; set; }
    	public byte[] ThumbNailPhoto { get; set; }
    	public string ThumbnailPhotoFileName { get; set; }
    	public byte[] LargePhoto { get; set; }
    	public string LargePhotoFileName { get; set; }
    	public System.DateTime ModifiedDate { get; set; }
    
    	public virtual ICollection<ProductProductPhoto> ProductProductPhotoes { get; set; }
    }
}
