//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adventureworks.Domain5
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ShipMethod
    {
    	public ShipMethod()
    	{
    		this.PurchaseOrderHeaders = new HashSet<PurchaseOrderHeader>();
    		this.SalesOrderHeaders = new HashSet<SalesOrderHeader>();
    	}
    
    	[Key]
		public int ShipMethodID { get; set; }
    	public string Name { get; set; }
    	public decimal ShipBase { get; set; }
    	public decimal ShipRate { get; set; }
    	public System.Guid rowguid { get; set; }
    	public System.DateTime ModifiedDate { get; set; }
    
    	public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
    	public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
    }
}
