//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adventureworks.WebMVC3.PurchasingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://adventureworks.com/purchasing/", ConfigurationName="PurchasingService.IPurchasingService")]
    public interface IPurchasingService {
        
        // CODEGEN: Generating message contract since the operation SubmitPurchasingProposal is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://adventureworks.com/purchasing/IPurchasingService/SubmitPurchasingProposal", ReplyAction="http://adventureworks.com/purchasing/IPurchasingService/SubmitPurchasingProposalR" +
            "esponse")]
        Adventureworks.WebMVC3.PurchasingService.SubmitPurchasingProposalResponse SubmitPurchasingProposal(Adventureworks.WebMVC3.PurchasingService.SubmitPurchasingProposalRequest request);
        
        // CODEGEN: Generating message contract since the operation SubmitVendorProposal is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://adventureworks.com/purchasing/IPurchasingService/SubmitVendorProposal", ReplyAction="http://adventureworks.com/purchasing/IPurchasingService/SubmitVendorProposalRespo" +
            "nse")]
        Adventureworks.WebMVC3.PurchasingService.SubmitVendorProposalResponse SubmitVendorProposal(Adventureworks.WebMVC3.PurchasingService.SubmitVendorProposalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitPurchasingProposalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adventureworks.com/contracts/purchasing", Order=0)]
        public Adventureworks.Domain.RequestForProposal RequestForProposal;
        
        public SubmitPurchasingProposalRequest() {
        }
        
        public SubmitPurchasingProposalRequest(Adventureworks.Domain.RequestForProposal RequestForProposal) {
            this.RequestForProposal = RequestForProposal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitPurchasingProposalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adventureworks.com/contracts/purchasing", Order=0)]
        public Adventureworks.Domain.ResponseForProposal ResponseForProposal;
        
        public SubmitPurchasingProposalResponse() {
        }
        
        public SubmitPurchasingProposalResponse(Adventureworks.Domain.ResponseForProposal ResponseForProposal) {
            this.ResponseForProposal = ResponseForProposal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitVendorProposalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adventureworks.com/contracts/purchasing", Order=0)]
        public Adventureworks.Domain.VendorSubmitProposalRequest VendorSubmitProposalRequest;
        
        public SubmitVendorProposalRequest() {
        }
        
        public SubmitVendorProposalRequest(Adventureworks.Domain.VendorSubmitProposalRequest VendorSubmitProposalRequest) {
            this.VendorSubmitProposalRequest = VendorSubmitProposalRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitVendorProposalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<bool> boolean;
        
        public SubmitVendorProposalResponse() {
        }
        
        public SubmitVendorProposalResponse(System.Nullable<bool> boolean) {
            this.boolean = boolean;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchasingServiceChannel : Adventureworks.WebMVC3.PurchasingService.IPurchasingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchasingServiceClient : System.ServiceModel.ClientBase<Adventureworks.WebMVC3.PurchasingService.IPurchasingService>, Adventureworks.WebMVC3.PurchasingService.IPurchasingService {
        
        public PurchasingServiceClient() {
        }
        
        public PurchasingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchasingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchasingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchasingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Adventureworks.WebMVC3.PurchasingService.SubmitPurchasingProposalResponse Adventureworks.WebMVC3.PurchasingService.IPurchasingService.SubmitPurchasingProposal(Adventureworks.WebMVC3.PurchasingService.SubmitPurchasingProposalRequest request) {
            return base.Channel.SubmitPurchasingProposal(request);
        }
        
        public Adventureworks.Domain.ResponseForProposal SubmitPurchasingProposal(Adventureworks.Domain.RequestForProposal RequestForProposal) {
            Adventureworks.WebMVC3.PurchasingService.SubmitPurchasingProposalRequest inValue = new Adventureworks.WebMVC3.PurchasingService.SubmitPurchasingProposalRequest();
            inValue.RequestForProposal = RequestForProposal;
            Adventureworks.WebMVC3.PurchasingService.SubmitPurchasingProposalResponse retVal = ((Adventureworks.WebMVC3.PurchasingService.IPurchasingService)(this)).SubmitPurchasingProposal(inValue);
            return retVal.ResponseForProposal;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Adventureworks.WebMVC3.PurchasingService.SubmitVendorProposalResponse Adventureworks.WebMVC3.PurchasingService.IPurchasingService.SubmitVendorProposal(Adventureworks.WebMVC3.PurchasingService.SubmitVendorProposalRequest request) {
            return base.Channel.SubmitVendorProposal(request);
        }
        
        public System.Nullable<bool> SubmitVendorProposal(Adventureworks.Domain.VendorSubmitProposalRequest VendorSubmitProposalRequest) {
            Adventureworks.WebMVC3.PurchasingService.SubmitVendorProposalRequest inValue = new Adventureworks.WebMVC3.PurchasingService.SubmitVendorProposalRequest();
            inValue.VendorSubmitProposalRequest = VendorSubmitProposalRequest;
            Adventureworks.WebMVC3.PurchasingService.SubmitVendorProposalResponse retVal = ((Adventureworks.WebMVC3.PurchasingService.IPurchasingService)(this)).SubmitVendorProposal(inValue);
            return retVal.boolean;
        }
    }
}
